# Generated by Django 5.0.3 on 2024-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='roles',
            field=models.ManyToManyField(related_name='projects', to='catalog.projectrole'),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.CharField(choices=[('EdTech', 'MEdTech')], max_length=50),
        ),
    ]
